### ISSUE TITLE
Support for 0.14 version

### ISSUE THREAD

**Issue by xgrommx** [intellij-purescript/intellij-purescript#157]
Hi, 0.14 have some improvements like explicit kind signatures and etc.
Will be added support for these features?

**Comment by Neppord** [comment]
At this point there is no fixed version at all that the plugin supports, most of its parser is from 2017, don't know what version of purescript was around then.

But since the plugin uses the current purescript parser as its reference i would assume that its 0.14 that we already are trying to target. However how close it is to 0.14 is hard to estimate. Try it out, se what don't work and contribute :). The code is not that scary anymore and there are helpful people that would love to help out on a pairing session, as long as the time zones overlap.
