### ISSUE TITLE
Doesn't have support polykinded kind constructors

### ISSUE THREAD

**Issue by xgrommx** [intellij-purescript/intellij-purescript#284]
Hello @Neppord

Thank you for support of optional names in type class instances.
Now I found new problem like doesn't have support for polykinded kind constructors (I mean `forall` in kind constructors)

For example

![image](https://user-images.githubusercontent.com/1499594/142729265-691abe2a-03df-42fd-b459-ae646a76b9fe.png)

**Comment by Neppord** [comment]
Is this only in foreign? or is this in other type definitions as well?

**Comment by Neppord** [comment]
Seams like we just need to reuse the `type` parser for the `parseForeignDeclaration`, instead of using `parseKind` which is not used in the purescript parser: https://github.com/purescript/purescript/blob/40d4a3d0635e8ad96220fe2d84ee511aad77dbbd/lib/purescript-cst/src/Language/PureScript/CST/Parser.y#L679

```
'foreign' 'import' ident '::' type
```

Our code:
```kotlin
    private val parseForeignDeclaration =
        token(FOREIGN) + token(IMPORT) + choice(
            (data + properName + dcolon + parseKind).`as`(ForeignDataDeclaration),
            (`'instance'` + ident + dcolon + optional(parseDeps)
                + attempt(qualified(properName)).`as`(Qualified).`as`(ClassName)
                + manyOrEmpty(typeAtom)
                ).`as`(PSElements.ExternInstanceDeclaration),
            (attempt(ident) + optional(attempt(string).`as`(PSElements.JSRaw))
                + dcolon + type).`as`(PSElements.ForeignValueDeclaration)
        )
```
