### ISSUE TITLE
Inspection "Missing Type Declaration" not listed in settings – can I disable?

### ISSUE THREAD

**Issue by baffalop** [intellij-purescript/intellij-purescript#392]
I would like to disable the Missing Type Declaration inspection, as it's quite obtrusive (background highlight) and I feel it's unnecessary for things like constants expressed with a simple literal.

It doesn't seem to be listed under Editor > Inspections, though:

![image](https://github.com/intellij-purescript/intellij-purescript/assets/33629446/fb2dfaa5-22fc-4a66-a9da-d7df7f71bd96)

Note that if I was able to disable it, I would still like to have an Intention (ie. in the alt+Enter menu) to add a type declaration.

Purescript plugin v0.81.6
PhpStorm 2023.2.3

**Comment by baffalop** [comment]
@Neppord Ok, I'm not quite sure what you mean by "from the IDE server"—do you know where I'd find the configuration for that?

**Comment by Neppord** [comment]
Purs IDE Rebuild is the inspection that creates the warnings for the missing type declaration.

I don't know if you can turn it off in the compiler, it's a compiler warning.

There might be possible to ignore it from the context menu.

I'll get back to you when I tried it.

**Comment by Neppord** [comment]
I have spent many hours (>16h) on trying to separate this inspection into its own configuration, and I haven't managed to do so.

The documentation around intentions, inspections and annotations is quite poor so i have tried to read a lot of source from other plugins. They gave all done things a little bit different from each other which makes it hard to reason about what does what etc. And throwing things on the wall and see what sticks haven't worked this time.

 You are free to try to solve this your self, and i would gladly help you in any way i can, but i can't put more time in to this issue, when there are more important and easier features to fix.
 
 Full support for the `purs ide` program is not a main goal for the plugin since re implementing the features inside the plugin instead would both make it more performant and better user experience. Improving the plugins typechecker would make this feature possible to port into the plugin and then it would be easier to make this inspection configurable.
